spring:
  application:
    name: team2

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      dialect : ${SPRING_JPA_PROPERTIES_HIBERNETE_DIALECT}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: validation
    encoding: ISO-8859-1
  sql:
    init:
      mode: always
      platform: mysql
taf:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000
    testAPI_url: ${TEST_API_SERVICE_URL}
    testAPI_port: ${TEST_API_SERVICE_PORT}
    selenium_container_url: ${SELENIUM_URL}
    selenium_container_port: ${SELENIUM_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_HOST}:${EUREKA_PORT}/eureka

openapi:
  service:
    version: 1.0.0
    url: http://${GATEWAY_HOST}:${GATEWAY_PORT} #api gateway url

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path:  /swagger-ui.html
  show-actuator: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false