server:
  servlet:
    context-path:
  port: ${PORT_USER:8080}

spring:
  application:
    name: user

  cloud:
    compatibility-verifier:
      enabled: false

  data:
    mongodb:
      uri: ${DB_URI}
      authentication-database: ${DB_AUTH}
      database: ${DB_NAME}
      auto-index-creation: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

taf:
  app:
    jwtSecret: ${API_TEST_TOKEN}
    jwtExpirationMs: ${API_TEST_EXP_TIME}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  #  prefer-ip-address: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_HOST}:${EUREKA_PORT}/eureka

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path:  /swagger-ui.html
    
endpoints:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true