services:
  backend:
    image: ${REGISTRY_BASE}/lionel-test-team1-backend:${BACKEND_VERSION}
    container_name: lionel-test-team1-backend
    ports:
      - "8083:8083"
    env_file:
      # Specifying the env file with necessaries values
      - .env
    depends_on:
      - mongodb
      - selenium

  frontend:
    image: ${REGISTRY_BASE}/lionel-test-team1-frontend:${FRONTEND_VERSION}
    container_name: lionel-test-team1-frontend
    ports:
      - "4200:80"
    env_file:
      - .env
    depends_on:
      - backend

  selenium:
    image: ${REGISTRY_BASE}/lionel-test-team1-selenium:${SELENIUM_VERSION}
    container_name: lionel-test-team1-selenium
    ports:
      - "8090:8090"

  testui:
    image: ${REGISTRY_BASE}/lionel-test-team1-testui:${TEST_UI_VERSION}
    container_name: lionel-test-team1-testui
    ports:
      - "4300:3000"

  testapi:
    image: ${REGISTRY_BASE}/lionel-test-team1-testapi:${TEST_API_VERSION}
    container_name: lionel-test-team1-testapi
    ports:
      - "8082:8082"
    env_file:
      - .env

  testuiteam4-server:
    image: ${REGISTRY_BASE}/lionel-test-team1-testui-team4-server:${TEST_TEAM4_SERVER_VERSION}
    container_name: lionel-test-team1-testuiteam4-server
    ports:
      - "8093:3000"
    env_file:
      - .env

  testuiteam4-client:
    image: ${REGISTRY_BASE}/lionel-test-team1-testui-team4-client:${TEST_TEAM4_CLIENT_VERSION}
    container_name: lionel-test-team1-testuiteam4-client
    ports:
      - "4400:3000"
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: lionel-test-team1-testuiteam4-mongo
    restart: always
    ports:
      - '47017:27017'
    volumes:
      - lionel-mongo2-data:/data/db
    env_file:
      # Specifying the env file with necessaries values
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  lionel-mongo2-data: