
##spring:
  #datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://nostrasoft.com:3306/nostr321_taf-db
    #username: nostr321_taf
    #password: JKaVLX75iHwtrHc
  #security:
    #enabled: false

spring:
  data:
    mongodb:
      uri: ${DB_URI}
      authentication-database: ${DB_AUTH}
      database: ${DB_NAME}
      auto-index-creation: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  messages:
    basename: validation
    encoding: ISO-8859-1

taf:
  app:
    jwtSecret: ${API_TEST_TOKEN}
    jwtExpirationMs: ${API_TEST_EXP_TIME}
    testAPI_url: ${API_TEST_URL}
    testAPI_port: ${API_TEST_PORT}
    #selenium_container_url: http://10.0.0.29 # URL correcte pour Selenium
    #selenium_container_port: 4444  # Port utilisé par Selenium Grid
    selenium_container_url: ${SELENIUM_URL}
    selenium_container_port: ${SELENIUM_PORT}

logging:
  level:
    #root: DEBUG
    #org.springframework: DEBUG
    #org.springframework.web: DEBUG
    org:
      mongodb:
        driver: DEBUG
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
        web:
          client:
            RestTemplate: DEBUG
          reactive:
            function:
              client:
                WebClient: DEBUG

server:
  port: 8083
  error:
    whitelabel:
      enabled: false
