server:
  servlet:
    context-path:
  port: ${PORT_GATEWAY:8080}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  #  prefer-ip-address: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_HOST}:${EUREKA_PORT}/eureka

springdoc:
  config-url: /custom-swagger-config
  api-docs:
    path: /api-docs
    config-url: /custom-swagger-config

  swagger-ui:
    disable-swagger-default-url: true
    config-url: /custom-swagger-config