spring:
  application:
    name: team3

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nostrasoft.com:3306/nostr321_taf-db
    username: nostr321_taf
    password: JKaVLX75iHwtrHc
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      dialect : ${spring.jpa.properties.hibernate.dialect}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: validation
    encoding: ISO-8859-1
  sql:
    init:
      mode: always
      platform: mysql
taf:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
    testAPI_url: http://localhost
    testAPI_port: 8082
    selenium_container_url: http://selenium
    selenium_container_port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_HOST}:${EUREKA_PORT}/eureka


openapi:
  service:
    version: 1.0.0
    url: http://${GATEWAY_HOST}:${GATEWAY_PORT} #api gateway url

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path:  /swagger-ui.html
  show-actuator: true

server:
  port: 8083