spring:
  application:
    name: team3

  cloud:
    compatibility-verifier:
      enabled: false

  data:
    mongodb:
      uri: ${DB_URI}
      authentication-database: ${DB_AUTH}
      database: ${DB_NAME}
      auto-index-creation: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  messages:
    basename: validation
    encoding: ISO-8859-1
      
taf:
  app:
    jwtSecret: ${API_TEST_TOKEN}
    jwtExpirationMs: ${API_TEST_EXP_TIME}
    testAPI_url: ${API_TEST_URL}
    testAPI_port: ${API_TEST_PORT}
    selenium_container_url: ${SELENIUM_URL}
    selenium_container_port: ${SELENIUM_PORT}

server:
  port: 8083
  error:
    whitelabel:
      enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  #  prefer-ip-address: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_HOST}:${EUREKA_PORT}/eureka

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path:  /swagger-ui.html