spring:
    application:
        name: eureka-server

    #main:
    #    web-application-type: reactive
    #    allow-bean-definition-overriding: true

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true

    security:
        user:
            name: ${EUREKA_USERNAME:eureka}
            password: ${EUREKA_PASSWORD:eureka}

server:
    port: ${EUREKA_PORT:8761}

eureka:
    instance:
        instance-id: ${spring.application.name}:${random.value}
        #prefer-ip-address: false
    client:
        register-with-eureka: false
        fetch-registry: false
        lease-renewal-interval-in-seconds: 30
    server:
        enable-self-preservation: true