services:
  selenium:
    image: ${REGISTRY_BASE}/lionel-test-team1-selenium:${SELENIUM_VERSION}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      API_TEST_TOKEN: ${API_TEST_TOKEN}
      API_TEST_EXP_TIME: ${API_TEST_EXP_TIME}
      API_TEST_URL: ${TEST_API3_SERVICE_URL}
      API_TEST_PORT: ${TEST_API3_SERVICE_PORT}
      SELENIUM_URL: ${SELENIUM3_URL}
      SELENIUM_PORT: ${SELENIUM3_PORT}
      EUREKA_HOST: ${EUREKA_HOST}
      EUREKA_PORT: ${EUREKA_PORT}
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}