services:
  gateway:
    image: ${REGISTRY_BASE}/lionel-test-gateway:${GATEWAY_VERSION}
    container_name: lionel-test-gateway
    depends_on:
      - registry
    ports:
      - "8762:8080"
    env_file:
      - .env