name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Java Checkstyle
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Checkstyle
        run: |
          ./gradlew checkstyleMain || true

      # Node.js for JS/TS/HTML/CSS linters
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --ext .js,.ts

      - name: Run Stylelint
        run: npx stylelint "**/*.{css,scss}"

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"

      - name: Run Hadolint (Dockerfile)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
